# Generated by Django 4.2.5 on 2023-09-25 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apps', '0002_blogarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
