# Generated by Django 4.2.5 on 2023-09-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apps', '0003_blogarticle_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogArticle',
            new_name='Article',
        ),
    ]
