# Generated by Django 4.2.5 on 2023-09-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apps', '0004_rename_blogarticle_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'articals'},
        ),
    ]
