# Generated by Django 4.2.5 on 2023-09-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_add',
            new_name='date_add',
        ),
    ]
