# Generated by Django 4.2.5 on 2023-09-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_data_add_entry_date_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
